from .. import Events, State, Supervisor

# Create states
q0_state = State("q0", True)
q10_state = State("q10", False)
q11_state = State("q11", False)
q12_state = State("q12", False)
q13_state = State("q13", False)
q14_state = State("q14", False)
q15_state = State("q15", False)
q16_state = State("q16", False)
q17_state = State("q17", False)
q18_state = State("q18", False)
q19_state = State("q19", False)
q2_state = State("q2", False)
q20_state = State("q20", False)
q21_state = State("q21", False)
q22_state = State("q22", False)
q23_state = State("q23", False)
q24_state = State("q24", False)
q25_state = State("q25", False)
q26_state = State("q26", False)
q27_state = State("q27", False)
q28_state = State("q28", False)
q29_state = State("q29", False)
q3_state = State("q3", False)
q30_state = State("q30", False)
q31_state = State("q31", False)
q32_state = State("q32", False)
q4_state = State("q4", False)
q5_state = State("q5", False)
q6_state = State("q6", False)
q7_state = State("q7", False)
q8_state = State("q8", False)
q9_state = State("q9", False)


# Create transitions
q0_state.add_transition(Events['stop'], q0_state)
q0_state.add_transition(Events['start'], q2_state)
q0_state.add_transition(Events['ppg_on'], q5_state)
q0_state.add_transition(Events['ppz_moving'], q9_state)
q10_state.add_transition(Events['start'], q10_state)
q10_state.add_transition(Events['ppg_on'], q14_state)
q10_state.add_transition(Events['ppz_stoped'], q2_state)
q10_state.add_transition(Events['cv1_on'], q27_state)
q10_state.add_transition(Events['stop'], q9_state)
q11_state.add_transition(Events['start'], q11_state)
q11_state.add_transition(Events['ppg_on'], q16_state)
q11_state.add_transition(Events['ppz_stoped'], q3_state)
q11_state.add_transition(Events['stop'], q9_state)
q12_state.add_transition(Events['start'], q12_state)
q12_state.add_transition(Events['stop'], q12_state)
q12_state.add_transition(Events['ppg_on'], q16_state)
q12_state.add_transition(Events['ppz_stoped'], q2_state)
q13_state.add_transition(Events['stop'], q13_state)
q13_state.add_transition(Events['start'], q14_state)
q13_state.add_transition(Events['ppz_stoped'], q5_state)
q13_state.add_transition(Events['ppg_off'], q9_state)
q14_state.add_transition(Events['ppg_off'], q10_state)
q14_state.add_transition(Events['stop'], q13_state)
q14_state.add_transition(Events['start'], q14_state)
q14_state.add_transition(Events['cv1_on'], q31_state)
q14_state.add_transition(Events['ppz_stoped'], q6_state)
q15_state.add_transition(Events['ppg_off'], q11_state)
q15_state.add_transition(Events['stop'], q13_state)
q15_state.add_transition(Events['start'], q15_state)
q15_state.add_transition(Events['ppz_stoped'], q7_state)
q16_state.add_transition(Events['ppg_off'], q12_state)
q16_state.add_transition(Events['start'], q16_state)
q16_state.add_transition(Events['stop'], q16_state)
q16_state.add_transition(Events['ppz_stoped'], q6_state)
q17_state.add_transition(Events['cv1_off'], q0_state)
q17_state.add_transition(Events['stop'], q17_state)
q17_state.add_transition(Events['start'], q18_state)
q17_state.add_transition(Events['ppg_on'], q21_state)
q17_state.add_transition(Events['ppz_moving'], q25_state)
q18_state.add_transition(Events['stop'], q17_state)
q18_state.add_transition(Events['start'], q18_state)
q18_state.add_transition(Events['cv1_off'], q2_state)
q18_state.add_transition(Events['ppg_on'], q22_state)
q18_state.add_transition(Events['ppz_moving'], q26_state)
q19_state.add_transition(Events['stop'], q17_state)
q19_state.add_transition(Events['start'], q19_state)
q19_state.add_transition(Events['ppg_on'], q24_state)
q19_state.add_transition(Events['ppz_moving'], q27_state)
q19_state.add_transition(Events['cv1_off'], q3_state)
q2_state.add_transition(Events['stop'], q0_state)
q2_state.add_transition(Events['ppz_moving'], q10_state)
q2_state.add_transition(Events['cv1_on'], q19_state)
q2_state.add_transition(Events['start'], q2_state)
q2_state.add_transition(Events['ppg_on'], q6_state)
q20_state.add_transition(Events['start'], q20_state)
q20_state.add_transition(Events['stop'], q20_state)
q20_state.add_transition(Events['ppg_on'], q24_state)
q20_state.add_transition(Events['ppz_moving'], q28_state)
q20_state.add_transition(Events['cv1_off'], q4_state)
q21_state.add_transition(Events['ppg_off'], q17_state)
q21_state.add_transition(Events['stop'], q21_state)
q21_state.add_transition(Events['start'], q22_state)
q21_state.add_transition(Events['ppz_moving'], q29_state)
q21_state.add_transition(Events['cv1_off'], q5_state)
q22_state.add_transition(Events['ppg_off'], q18_state)
q22_state.add_transition(Events['stop'], q21_state)
q22_state.add_transition(Events['start'], q22_state)
q22_state.add_transition(Events['ppz_moving'], q30_state)
q22_state.add_transition(Events['cv1_off'], q6_state)
q23_state.add_transition(Events['ppg_off'], q19_state)
q23_state.add_transition(Events['stop'], q21_state)
q23_state.add_transition(Events['start'], q23_state)
q23_state.add_transition(Events['ppz_moving'], q31_state)
q23_state.add_transition(Events['cv1_off'], q7_state)
q24_state.add_transition(Events['ppg_off'], q20_state)
q24_state.add_transition(Events['start'], q24_state)
q24_state.add_transition(Events['stop'], q24_state)
q24_state.add_transition(Events['ppz_moving'], q32_state)
q24_state.add_transition(Events['cv1_off'], q8_state)
q25_state.add_transition(Events['ppz_stoped'], q17_state)
q25_state.add_transition(Events['stop'], q25_state)
q25_state.add_transition(Events['start'], q26_state)
q25_state.add_transition(Events['ppg_on'], q29_state)
q25_state.add_transition(Events['cv1_off'], q9_state)
q26_state.add_transition(Events['cv1_off'], q10_state)
q26_state.add_transition(Events['ppz_stoped'], q18_state)
q26_state.add_transition(Events['stop'], q25_state)
q26_state.add_transition(Events['start'], q26_state)
q26_state.add_transition(Events['ppg_on'], q30_state)
q27_state.add_transition(Events['cv1_off'], q11_state)
q27_state.add_transition(Events['ppz_stoped'], q19_state)
q27_state.add_transition(Events['stop'], q25_state)
q27_state.add_transition(Events['start'], q27_state)
q27_state.add_transition(Events['ppg_on'], q32_state)
q28_state.add_transition(Events['cv1_off'], q12_state)
q28_state.add_transition(Events['ppz_stoped'], q18_state)
q28_state.add_transition(Events['start'], q28_state)
q28_state.add_transition(Events['stop'], q28_state)
q28_state.add_transition(Events['ppg_on'], q32_state)
q29_state.add_transition(Events['cv1_off'], q13_state)
q29_state.add_transition(Events['ppz_stoped'], q21_state)
q29_state.add_transition(Events['ppg_off'], q25_state)
q29_state.add_transition(Events['stop'], q29_state)
q29_state.add_transition(Events['start'], q30_state)
q3_state.add_transition(Events['stop'], q0_state)
q3_state.add_transition(Events['ppz_moving'], q11_state)
q3_state.add_transition(Events['start'], q3_state)
q3_state.add_transition(Events['ppg_on'], q8_state)
q30_state.add_transition(Events['cv1_off'], q14_state)
q30_state.add_transition(Events['ppz_stoped'], q22_state)
q30_state.add_transition(Events['ppg_off'], q26_state)
q30_state.add_transition(Events['stop'], q29_state)
q30_state.add_transition(Events['start'], q30_state)
q31_state.add_transition(Events['cv1_off'], q15_state)
q31_state.add_transition(Events['ppz_stoped'], q23_state)
q31_state.add_transition(Events['ppg_off'], q27_state)
q31_state.add_transition(Events['stop'], q29_state)
q31_state.add_transition(Events['start'], q31_state)
q32_state.add_transition(Events['cv1_off'], q16_state)
q32_state.add_transition(Events['ppz_stoped'], q22_state)
q32_state.add_transition(Events['ppg_off'], q28_state)
q32_state.add_transition(Events['start'], q32_state)
q32_state.add_transition(Events['stop'], q32_state)
q4_state.add_transition(Events['ppz_moving'], q12_state)
q4_state.add_transition(Events['start'], q4_state)
q4_state.add_transition(Events['stop'], q4_state)
q4_state.add_transition(Events['ppg_on'], q8_state)
q5_state.add_transition(Events['ppg_off'], q0_state)
q5_state.add_transition(Events['ppz_moving'], q13_state)
q5_state.add_transition(Events['stop'], q5_state)
q5_state.add_transition(Events['start'], q6_state)
q6_state.add_transition(Events['ppz_moving'], q14_state)
q6_state.add_transition(Events['ppg_off'], q2_state)
q6_state.add_transition(Events['cv1_on'], q23_state)
q6_state.add_transition(Events['stop'], q5_state)
q6_state.add_transition(Events['start'], q6_state)
q7_state.add_transition(Events['ppz_moving'], q15_state)
q7_state.add_transition(Events['ppg_off'], q3_state)
q7_state.add_transition(Events['stop'], q5_state)
q7_state.add_transition(Events['start'], q7_state)
q8_state.add_transition(Events['ppz_moving'], q16_state)
q8_state.add_transition(Events['ppg_off'], q4_state)
q8_state.add_transition(Events['start'], q8_state)
q8_state.add_transition(Events['stop'], q8_state)
q9_state.add_transition(Events['ppz_stoped'], q0_state)
q9_state.add_transition(Events['start'], q10_state)
q9_state.add_transition(Events['ppg_on'], q13_state)
q9_state.add_transition(Events['stop'], q9_state)


# create state list
state_list = []
state_list.append(q0_state)
state_list.append(q10_state)
state_list.append(q11_state)
state_list.append(q12_state)
state_list.append(q13_state)
state_list.append(q14_state)
state_list.append(q15_state)
state_list.append(q16_state)
state_list.append(q17_state)
state_list.append(q18_state)
state_list.append(q19_state)
state_list.append(q2_state)
state_list.append(q20_state)
state_list.append(q21_state)
state_list.append(q22_state)
state_list.append(q23_state)
state_list.append(q24_state)
state_list.append(q25_state)
state_list.append(q26_state)
state_list.append(q27_state)
state_list.append(q28_state)
state_list.append(q29_state)
state_list.append(q3_state)
state_list.append(q30_state)
state_list.append(q31_state)
state_list.append(q32_state)
state_list.append(q4_state)
state_list.append(q5_state)
state_list.append(q6_state)
state_list.append(q7_state)
state_list.append(q8_state)
state_list.append(q9_state)


# create event list
alphabet = []
alphabet.append(Events['stop'])
alphabet.append(Events['start'])
alphabet.append(Events['ppg_on'])
alphabet.append(Events['ppz_moving'])
alphabet.append(Events['ppz_stoped'])
alphabet.append(Events['cv1_on'])
alphabet.append(Events['ppg_off'])
alphabet.append(Events['cv1_off'])


# create supervisor
se01_liga_cv1 = Supervisor("se01_liga_cv1", state_list, alphabet)