from .. import Events, State, Supervisor

# Create states
q0_state = State("q0", True)
q1_state = State("q1", False)
q10_state = State("q10", False)
q11_state = State("q11", False)
q12_state = State("q12", False)
q13_state = State("q13", False)
q14_state = State("q14", False)
q15_state = State("q15", False)
q16_state = State("q16", False)
q17_state = State("q17", False)
q18_state = State("q18", False)
q19_state = State("q19", False)
q20_state = State("q20", False)
q21_state = State("q21", False)
q22_state = State("q22", False)
q23_state = State("q23", False)
q24_state = State("q24", False)
q25_state = State("q25", False)
q26_state = State("q26", False)
q27_state = State("q27", False)
q28_state = State("q28", False)
q29_state = State("q29", False)
q3_state = State("q3", False)
q30_state = State("q30", False)
q31_state = State("q31", False)
q32_state = State("q32", False)
q33_state = State("q33", False)
q34_state = State("q34", False)
q35_state = State("q35", False)
q36_state = State("q36", False)
q37_state = State("q37", False)
q38_state = State("q38", False)
q39_state = State("q39", False)
q4_state = State("q4", False)
q40_state = State("q40", False)
q5_state = State("q5", False)
q6_state = State("q6", False)
q7_state = State("q7", False)
q8_state = State("q8", False)
q9_state = State("q9", False)


# Create transitions
q0_state.add_transition(Events['ppx_on'], q14_state)
q0_state.add_transition(Events['s1'], q3_state)
q0_state.add_transition(Events['ppx_moving'], q7_state)
q1_state.add_transition(Events['s1'], q0_state)
q1_state.add_transition(Events['ppx_on'], q11_state)
q1_state.add_transition(Events['ppx_moving'], q6_state)
q10_state.add_transition(Events['s1'], q10_state)
q10_state.add_transition(Events['ppx_on'], q20_state)
q10_state.add_transition(Events['ppz_on'], q26_state)
q10_state.add_transition(Events['ppx_stoped'], q5_state)
q11_state.add_transition(Events['ppx_off'], q1_state)
q11_state.add_transition(Events['s1'], q12_state)
q11_state.add_transition(Events['ppx_moving'], q16_state)
q12_state.add_transition(Events['ppx_off'], q0_state)
q12_state.add_transition(Events['s1'], q13_state)
q12_state.add_transition(Events['ppx_moving'], q17_state)
q13_state.add_transition(Events['s1'], q13_state)
q13_state.add_transition(Events['ppx_moving'], q18_state)
q13_state.add_transition(Events['ppx_off'], q3_state)
q13_state.add_transition(Events['ppz_on'], q32_state)
q14_state.add_transition(Events['s1'], q14_state)
q14_state.add_transition(Events['ppx_moving'], q19_state)
q14_state.add_transition(Events['ppx_off'], q4_state)
q15_state.add_transition(Events['s1'], q15_state)
q15_state.add_transition(Events['ppx_moving'], q20_state)
q15_state.add_transition(Events['ppz_on'], q31_state)
q15_state.add_transition(Events['ppx_off'], q5_state)
q16_state.add_transition(Events['ppx_stoped'], q12_state)
q16_state.add_transition(Events['s1'], q17_state)
q16_state.add_transition(Events['ppx_off'], q6_state)
q17_state.add_transition(Events['ppx_stoped'], q13_state)
q17_state.add_transition(Events['s1'], q18_state)
q17_state.add_transition(Events['ppx_off'], q7_state)
q18_state.add_transition(Events['ppx_stoped'], q13_state)
q18_state.add_transition(Events['s1'], q18_state)
q18_state.add_transition(Events['ppz_on'], q37_state)
q18_state.add_transition(Events['ppx_off'], q8_state)
q19_state.add_transition(Events['ppx_stoped'], q15_state)
q19_state.add_transition(Events['s1'], q19_state)
q19_state.add_transition(Events['ppx_off'], q9_state)
q20_state.add_transition(Events['ppx_off'], q10_state)
q20_state.add_transition(Events['ppx_stoped'], q15_state)
q20_state.add_transition(Events['s1'], q20_state)
q20_state.add_transition(Events['ppz_on'], q36_state)
q21_state.add_transition(Events['ppz_off'], q1_state)
q21_state.add_transition(Events['s1'], q22_state)
q21_state.add_transition(Events['ppx_moving'], q26_state)
q21_state.add_transition(Events['ppx_on'], q31_state)
q22_state.add_transition(Events['ppz_off'], q0_state)
q22_state.add_transition(Events['s1'], q23_state)
q22_state.add_transition(Events['ppx_moving'], q27_state)
q22_state.add_transition(Events['ppx_on'], q34_state)
q23_state.add_transition(Events['s1'], q23_state)
q23_state.add_transition(Events['ppx_moving'], q28_state)
q23_state.add_transition(Events['ppz_off'], q3_state)
q23_state.add_transition(Events['ppx_on'], q33_state)
q24_state.add_transition(Events['s1'], q24_state)
q24_state.add_transition(Events['ppx_moving'], q29_state)
q24_state.add_transition(Events['ppx_on'], q34_state)
q24_state.add_transition(Events['ppz_off'], q4_state)
q25_state.add_transition(Events['s1'], q25_state)
q25_state.add_transition(Events['ppx_moving'], q30_state)
q25_state.add_transition(Events['ppx_on'], q35_state)
q25_state.add_transition(Events['ppz_off'], q5_state)
q26_state.add_transition(Events['ppx_stoped'], q22_state)
q26_state.add_transition(Events['s1'], q27_state)
q26_state.add_transition(Events['ppx_on'], q36_state)
q26_state.add_transition(Events['ppz_off'], q6_state)
q27_state.add_transition(Events['ppx_stoped'], q23_state)
q27_state.add_transition(Events['s1'], q28_state)
q27_state.add_transition(Events['ppx_on'], q39_state)
q27_state.add_transition(Events['ppz_off'], q7_state)
q28_state.add_transition(Events['ppx_stoped'], q23_state)
q28_state.add_transition(Events['s1'], q28_state)
q28_state.add_transition(Events['ppx_on'], q38_state)
q28_state.add_transition(Events['ppz_off'], q8_state)
q29_state.add_transition(Events['ppx_stoped'], q25_state)
q29_state.add_transition(Events['s1'], q29_state)
q29_state.add_transition(Events['ppx_on'], q39_state)
q29_state.add_transition(Events['ppz_off'], q9_state)
q3_state.add_transition(Events['ppx_on'], q13_state)
q3_state.add_transition(Events['ppz_on'], q22_state)
q3_state.add_transition(Events['s1'], q3_state)
q3_state.add_transition(Events['ppx_moving'], q8_state)
q30_state.add_transition(Events['ppz_off'], q10_state)
q30_state.add_transition(Events['ppx_stoped'], q25_state)
q30_state.add_transition(Events['s1'], q30_state)
q30_state.add_transition(Events['ppx_on'], q40_state)
q31_state.add_transition(Events['ppz_off'], q11_state)
q31_state.add_transition(Events['ppx_off'], q21_state)
q31_state.add_transition(Events['s1'], q32_state)
q31_state.add_transition(Events['ppx_moving'], q36_state)
q32_state.add_transition(Events['ppz_off'], q12_state)
q32_state.add_transition(Events['ppx_off'], q22_state)
q32_state.add_transition(Events['s1'], q33_state)
q32_state.add_transition(Events['ppx_moving'], q37_state)
q33_state.add_transition(Events['ppz_off'], q13_state)
q33_state.add_transition(Events['ppx_off'], q23_state)
q33_state.add_transition(Events['s1'], q33_state)
q33_state.add_transition(Events['ppx_moving'], q38_state)
q34_state.add_transition(Events['ppz_off'], q14_state)
q34_state.add_transition(Events['ppx_off'], q24_state)
q34_state.add_transition(Events['s1'], q34_state)
q34_state.add_transition(Events['ppx_moving'], q39_state)
q35_state.add_transition(Events['ppz_off'], q15_state)
q35_state.add_transition(Events['ppx_off'], q25_state)
q35_state.add_transition(Events['s1'], q35_state)
q35_state.add_transition(Events['ppx_moving'], q40_state)
q36_state.add_transition(Events['ppz_off'], q16_state)
q36_state.add_transition(Events['ppx_off'], q26_state)
q36_state.add_transition(Events['ppx_stoped'], q32_state)
q36_state.add_transition(Events['s1'], q37_state)
q37_state.add_transition(Events['ppz_off'], q17_state)
q37_state.add_transition(Events['ppx_off'], q27_state)
q37_state.add_transition(Events['ppx_stoped'], q33_state)
q37_state.add_transition(Events['s1'], q38_state)
q38_state.add_transition(Events['ppz_off'], q18_state)
q38_state.add_transition(Events['ppx_off'], q28_state)
q38_state.add_transition(Events['ppx_stoped'], q33_state)
q38_state.add_transition(Events['s1'], q38_state)
q39_state.add_transition(Events['ppz_off'], q19_state)
q39_state.add_transition(Events['ppx_off'], q29_state)
q39_state.add_transition(Events['ppx_stoped'], q35_state)
q39_state.add_transition(Events['s1'], q39_state)
q4_state.add_transition(Events['ppx_on'], q14_state)
q4_state.add_transition(Events['s1'], q4_state)
q4_state.add_transition(Events['ppx_moving'], q9_state)
q40_state.add_transition(Events['ppz_off'], q20_state)
q40_state.add_transition(Events['ppx_off'], q30_state)
q40_state.add_transition(Events['ppx_stoped'], q35_state)
q40_state.add_transition(Events['s1'], q40_state)
q5_state.add_transition(Events['ppx_moving'], q10_state)
q5_state.add_transition(Events['ppx_on'], q15_state)
q5_state.add_transition(Events['ppz_on'], q21_state)
q5_state.add_transition(Events['s1'], q5_state)
q6_state.add_transition(Events['ppx_stoped'], q0_state)
q6_state.add_transition(Events['ppx_on'], q16_state)
q6_state.add_transition(Events['s1'], q7_state)
q7_state.add_transition(Events['ppx_on'], q19_state)
q7_state.add_transition(Events['ppx_stoped'], q3_state)
q7_state.add_transition(Events['s1'], q8_state)
q8_state.add_transition(Events['ppx_on'], q18_state)
q8_state.add_transition(Events['ppz_on'], q27_state)
q8_state.add_transition(Events['ppx_stoped'], q3_state)
q8_state.add_transition(Events['s1'], q8_state)
q9_state.add_transition(Events['ppx_on'], q19_state)
q9_state.add_transition(Events['ppx_stoped'], q5_state)
q9_state.add_transition(Events['s1'], q9_state)


# create state list
state_list = []
state_list.append(q0_state)
state_list.append(q1_state)
state_list.append(q10_state)
state_list.append(q11_state)
state_list.append(q12_state)
state_list.append(q13_state)
state_list.append(q14_state)
state_list.append(q15_state)
state_list.append(q16_state)
state_list.append(q17_state)
state_list.append(q18_state)
state_list.append(q19_state)
state_list.append(q20_state)
state_list.append(q21_state)
state_list.append(q22_state)
state_list.append(q23_state)
state_list.append(q24_state)
state_list.append(q25_state)
state_list.append(q26_state)
state_list.append(q27_state)
state_list.append(q28_state)
state_list.append(q29_state)
state_list.append(q3_state)
state_list.append(q30_state)
state_list.append(q31_state)
state_list.append(q32_state)
state_list.append(q33_state)
state_list.append(q34_state)
state_list.append(q35_state)
state_list.append(q36_state)
state_list.append(q37_state)
state_list.append(q38_state)
state_list.append(q39_state)
state_list.append(q4_state)
state_list.append(q40_state)
state_list.append(q5_state)
state_list.append(q6_state)
state_list.append(q7_state)
state_list.append(q8_state)
state_list.append(q9_state)


# create event list
alphabet = []
alphabet.append(Events['ppx_on'])
alphabet.append(Events['s1'])
alphabet.append(Events['ppx_moving'])
alphabet.append(Events['ppz_on'])
alphabet.append(Events['ppx_stoped'])
alphabet.append(Events['ppx_off'])
alphabet.append(Events['ppz_off'])


# create supervisor
se02_desce_braco = Supervisor("se02_desce_braco", state_list, alphabet)