from .. import Events, State, Supervisor

# Create states
q0_state = State("q0", True)
q10_state = State("q10", False)
q11_state = State("q11", False)
q12_state = State("q12", False)
q13_state = State("q13", False)
q14_state = State("q14", False)
q15_state = State("q15", False)
q16_state = State("q16", False)
q17_state = State("q17", False)
q18_state = State("q18", False)
q19_state = State("q19", False)
q2_state = State("q2", False)
q20_state = State("q20", False)
q21_state = State("q21", False)
q22_state = State("q22", False)
q23_state = State("q23", False)
q24_state = State("q24", False)
q3_state = State("q3", False)
q4_state = State("q4", False)
q5_state = State("q5", False)
q6_state = State("q6", False)
q7_state = State("q7", False)
q8_state = State("q8", False)
q9_state = State("q9", False)


# Create transitions
q0_state.add_transition(Events['ppz_on'], q13_state)
q0_state.add_transition(Events['cv2_on'], q4_state)
q0_state.add_transition(Events['ppx_on'], q8_state)
q10_state.add_transition(Events['ppz_on'], q22_state)
q10_state.add_transition(Events['ppx_off'], q4_state)
q11_state.add_transition(Events['ppz_on'], q24_state)
q11_state.add_transition(Events['ppx_off'], q5_state)
q12_state.add_transition(Events['ppz_on'], q24_state)
q12_state.add_transition(Events['ppx_off'], q6_state)
q12_state.add_transition(Events['cv2_off'], q7_state)
q13_state.add_transition(Events['ppz_off'], q0_state)
q13_state.add_transition(Events['cv2_on'], q16_state)
q13_state.add_transition(Events['ppx_on'], q20_state)
q14_state.add_transition(Events['cv2_on'], q17_state)
q14_state.add_transition(Events['ppz_off'], q2_state)
q14_state.add_transition(Events['ppx_on'], q20_state)
q15_state.add_transition(Events['cv2_on'], q16_state)
q15_state.add_transition(Events['ppx_on'], q21_state)
q15_state.add_transition(Events['ppz_off'], q3_state)
q16_state.add_transition(Events['ppx_on'], q23_state)
q16_state.add_transition(Events['ppz_off'], q4_state)
q17_state.add_transition(Events['ppx_on'], q23_state)
q17_state.add_transition(Events['ppz_off'], q5_state)
q18_state.add_transition(Events['cv2_off'], q13_state)
q18_state.add_transition(Events['ppx_on'], q24_state)
q18_state.add_transition(Events['ppz_off'], q6_state)
q19_state.add_transition(Events['ppx_off'], q13_state)
q19_state.add_transition(Events['cv2_on'], q22_state)
q19_state.add_transition(Events['ppz_off'], q7_state)
q2_state.add_transition(Events['ppz_on'], q15_state)
q2_state.add_transition(Events['cv2_on'], q5_state)
q2_state.add_transition(Events['ppx_on'], q8_state)
q20_state.add_transition(Events['ppx_off'], q14_state)
q20_state.add_transition(Events['cv2_on'], q23_state)
q20_state.add_transition(Events['ppz_off'], q8_state)
q21_state.add_transition(Events['ppx_off'], q15_state)
q21_state.add_transition(Events['cv2_on'], q22_state)
q21_state.add_transition(Events['ppz_off'], q9_state)
q22_state.add_transition(Events['ppz_off'], q10_state)
q22_state.add_transition(Events['ppx_off'], q16_state)
q23_state.add_transition(Events['ppz_off'], q11_state)
q23_state.add_transition(Events['ppx_off'], q17_state)
q24_state.add_transition(Events['ppz_off'], q12_state)
q24_state.add_transition(Events['ppx_off'], q18_state)
q24_state.add_transition(Events['cv2_off'], q19_state)
q3_state.add_transition(Events['ppz_on'], q15_state)
q3_state.add_transition(Events['cv2_on'], q4_state)
q3_state.add_transition(Events['ppx_on'], q9_state)
q4_state.add_transition(Events['ppx_on'], q11_state)
q4_state.add_transition(Events['ppz_on'], q16_state)
q5_state.add_transition(Events['ppx_on'], q11_state)
q5_state.add_transition(Events['ppz_on'], q18_state)
q6_state.add_transition(Events['cv2_off'], q0_state)
q6_state.add_transition(Events['ppx_on'], q12_state)
q6_state.add_transition(Events['ppz_on'], q18_state)
q7_state.add_transition(Events['ppx_off'], q0_state)
q7_state.add_transition(Events['cv2_on'], q10_state)
q7_state.add_transition(Events['ppz_on'], q19_state)
q8_state.add_transition(Events['cv2_on'], q11_state)
q8_state.add_transition(Events['ppx_off'], q2_state)
q8_state.add_transition(Events['ppz_on'], q21_state)
q9_state.add_transition(Events['cv2_on'], q10_state)
q9_state.add_transition(Events['ppz_on'], q21_state)
q9_state.add_transition(Events['ppx_off'], q3_state)


# create state list
state_list = []
state_list.append(q0_state)
state_list.append(q10_state)
state_list.append(q11_state)
state_list.append(q12_state)
state_list.append(q13_state)
state_list.append(q14_state)
state_list.append(q15_state)
state_list.append(q16_state)
state_list.append(q17_state)
state_list.append(q18_state)
state_list.append(q19_state)
state_list.append(q2_state)
state_list.append(q20_state)
state_list.append(q21_state)
state_list.append(q22_state)
state_list.append(q23_state)
state_list.append(q24_state)
state_list.append(q3_state)
state_list.append(q4_state)
state_list.append(q5_state)
state_list.append(q6_state)
state_list.append(q7_state)
state_list.append(q8_state)
state_list.append(q9_state)


# create event list
alphabet = []
alphabet.append(Events['ppz_on'])
alphabet.append(Events['cv2_on'])
alphabet.append(Events['ppx_on'])
alphabet.append(Events['ppx_off'])
alphabet.append(Events['cv2_off'])
alphabet.append(Events['ppz_off'])


# create supervisor
se05_desliga_cv2 = Supervisor("se05_desliga_cv2", state_list, alphabet)