from .. import Events, State, Supervisor

# Create states
q0_state = State("q0", True)
q10_state = State("q10", False)
q11_state = State("q11", False)
q12_state = State("q12", False)
q13_state = State("q13", False)
q14_state = State("q14", False)
q15_state = State("q15", False)
q16_state = State("q16", False)
q17_state = State("q17", False)
q18_state = State("q18", False)
q19_state = State("q19", False)
q2_state = State("q2", False)
q20_state = State("q20", False)
q21_state = State("q21", False)
q22_state = State("q22", False)
q23_state = State("q23", False)
q24_state = State("q24", False)
q25_state = State("q25", False)
q26_state = State("q26", False)
q27_state = State("q27", False)
q28_state = State("q28", False)
q29_state = State("q29", False)
q3_state = State("q3", False)
q30_state = State("q30", False)
q31_state = State("q31", False)
q32_state = State("q32", False)
q4_state = State("q4", False)
q5_state = State("q5", False)
q6_state = State("q6", False)
q7_state = State("q7", False)
q8_state = State("q8", False)
q9_state = State("q9", False)


# Create transitions
q0_state.add_transition(Events['t4'], q0_state)
q0_state.add_transition(Events['t3'], q2_state)
q0_state.add_transition(Events['s5'], q5_state)
q0_state.add_transition(Events['m6'], q9_state)
q10_state.add_transition(Events['t3'], q10_state)
q10_state.add_transition(Events['s5'], q14_state)
q10_state.add_transition(Events['p6'], q2_state)
q10_state.add_transition(Events['s1'], q27_state)
q10_state.add_transition(Events['t4'], q9_state)
q11_state.add_transition(Events['t3'], q11_state)
q11_state.add_transition(Events['s5'], q16_state)
q11_state.add_transition(Events['p6'], q3_state)
q11_state.add_transition(Events['t4'], q9_state)
q12_state.add_transition(Events['t3'], q12_state)
q12_state.add_transition(Events['t4'], q12_state)
q12_state.add_transition(Events['s5'], q16_state)
q12_state.add_transition(Events['p6'], q2_state)
q13_state.add_transition(Events['t4'], q13_state)
q13_state.add_transition(Events['t3'], q14_state)
q13_state.add_transition(Events['p6'], q5_state)
q13_state.add_transition(Events['f5'], q9_state)
q14_state.add_transition(Events['f5'], q10_state)
q14_state.add_transition(Events['t4'], q13_state)
q14_state.add_transition(Events['t3'], q14_state)
q14_state.add_transition(Events['s1'], q31_state)
q14_state.add_transition(Events['p6'], q6_state)
q15_state.add_transition(Events['f5'], q11_state)
q15_state.add_transition(Events['t4'], q13_state)
q15_state.add_transition(Events['t3'], q15_state)
q15_state.add_transition(Events['p6'], q7_state)
q16_state.add_transition(Events['f5'], q12_state)
q16_state.add_transition(Events['t3'], q16_state)
q16_state.add_transition(Events['t4'], q16_state)
q16_state.add_transition(Events['p6'], q6_state)
q17_state.add_transition(Events['f1'], q0_state)
q17_state.add_transition(Events['t4'], q17_state)
q17_state.add_transition(Events['t3'], q18_state)
q17_state.add_transition(Events['s5'], q21_state)
q17_state.add_transition(Events['m6'], q25_state)
q18_state.add_transition(Events['t4'], q17_state)
q18_state.add_transition(Events['t3'], q18_state)
q18_state.add_transition(Events['f1'], q2_state)
q18_state.add_transition(Events['s5'], q22_state)
q18_state.add_transition(Events['m6'], q26_state)
q19_state.add_transition(Events['t4'], q17_state)
q19_state.add_transition(Events['t3'], q19_state)
q19_state.add_transition(Events['s5'], q24_state)
q19_state.add_transition(Events['m6'], q27_state)
q19_state.add_transition(Events['f1'], q3_state)
q2_state.add_transition(Events['t4'], q0_state)
q2_state.add_transition(Events['m6'], q10_state)
q2_state.add_transition(Events['s1'], q19_state)
q2_state.add_transition(Events['t3'], q2_state)
q2_state.add_transition(Events['s5'], q6_state)
q20_state.add_transition(Events['t3'], q20_state)
q20_state.add_transition(Events['t4'], q20_state)
q20_state.add_transition(Events['s5'], q24_state)
q20_state.add_transition(Events['m6'], q28_state)
q20_state.add_transition(Events['f1'], q4_state)
q21_state.add_transition(Events['f5'], q17_state)
q21_state.add_transition(Events['t4'], q21_state)
q21_state.add_transition(Events['t3'], q22_state)
q21_state.add_transition(Events['m6'], q29_state)
q21_state.add_transition(Events['f1'], q5_state)
q22_state.add_transition(Events['f5'], q18_state)
q22_state.add_transition(Events['t4'], q21_state)
q22_state.add_transition(Events['t3'], q22_state)
q22_state.add_transition(Events['m6'], q30_state)
q22_state.add_transition(Events['f1'], q6_state)
q23_state.add_transition(Events['f5'], q19_state)
q23_state.add_transition(Events['t4'], q21_state)
q23_state.add_transition(Events['t3'], q23_state)
q23_state.add_transition(Events['m6'], q31_state)
q23_state.add_transition(Events['f1'], q7_state)
q24_state.add_transition(Events['f5'], q20_state)
q24_state.add_transition(Events['t3'], q24_state)
q24_state.add_transition(Events['t4'], q24_state)
q24_state.add_transition(Events['m6'], q32_state)
q24_state.add_transition(Events['f1'], q8_state)
q25_state.add_transition(Events['p6'], q17_state)
q25_state.add_transition(Events['t4'], q25_state)
q25_state.add_transition(Events['t3'], q26_state)
q25_state.add_transition(Events['s5'], q29_state)
q25_state.add_transition(Events['f1'], q9_state)
q26_state.add_transition(Events['f1'], q10_state)
q26_state.add_transition(Events['p6'], q18_state)
q26_state.add_transition(Events['t4'], q25_state)
q26_state.add_transition(Events['t3'], q26_state)
q26_state.add_transition(Events['s5'], q30_state)
q27_state.add_transition(Events['f1'], q11_state)
q27_state.add_transition(Events['p6'], q19_state)
q27_state.add_transition(Events['t4'], q25_state)
q27_state.add_transition(Events['t3'], q27_state)
q27_state.add_transition(Events['s5'], q32_state)
q28_state.add_transition(Events['f1'], q12_state)
q28_state.add_transition(Events['p6'], q18_state)
q28_state.add_transition(Events['t3'], q28_state)
q28_state.add_transition(Events['t4'], q28_state)
q28_state.add_transition(Events['s5'], q32_state)
q29_state.add_transition(Events['f1'], q13_state)
q29_state.add_transition(Events['p6'], q21_state)
q29_state.add_transition(Events['f5'], q25_state)
q29_state.add_transition(Events['t4'], q29_state)
q29_state.add_transition(Events['t3'], q30_state)
q3_state.add_transition(Events['t4'], q0_state)
q3_state.add_transition(Events['m6'], q11_state)
q3_state.add_transition(Events['t3'], q3_state)
q3_state.add_transition(Events['s5'], q8_state)
q30_state.add_transition(Events['f1'], q14_state)
q30_state.add_transition(Events['p6'], q22_state)
q30_state.add_transition(Events['f5'], q26_state)
q30_state.add_transition(Events['t4'], q29_state)
q30_state.add_transition(Events['t3'], q30_state)
q31_state.add_transition(Events['f1'], q15_state)
q31_state.add_transition(Events['p6'], q23_state)
q31_state.add_transition(Events['f5'], q27_state)
q31_state.add_transition(Events['t4'], q29_state)
q31_state.add_transition(Events['t3'], q31_state)
q32_state.add_transition(Events['f1'], q16_state)
q32_state.add_transition(Events['p6'], q22_state)
q32_state.add_transition(Events['f5'], q28_state)
q32_state.add_transition(Events['t3'], q32_state)
q32_state.add_transition(Events['t4'], q32_state)
q4_state.add_transition(Events['m6'], q12_state)
q4_state.add_transition(Events['t3'], q4_state)
q4_state.add_transition(Events['t4'], q4_state)
q4_state.add_transition(Events['s5'], q8_state)
q5_state.add_transition(Events['f5'], q0_state)
q5_state.add_transition(Events['m6'], q13_state)
q5_state.add_transition(Events['t4'], q5_state)
q5_state.add_transition(Events['t3'], q6_state)
q6_state.add_transition(Events['m6'], q14_state)
q6_state.add_transition(Events['f5'], q2_state)
q6_state.add_transition(Events['s1'], q23_state)
q6_state.add_transition(Events['t4'], q5_state)
q6_state.add_transition(Events['t3'], q6_state)
q7_state.add_transition(Events['m6'], q15_state)
q7_state.add_transition(Events['f5'], q3_state)
q7_state.add_transition(Events['t4'], q5_state)
q7_state.add_transition(Events['t3'], q7_state)
q8_state.add_transition(Events['m6'], q16_state)
q8_state.add_transition(Events['f5'], q4_state)
q8_state.add_transition(Events['t3'], q8_state)
q8_state.add_transition(Events['t4'], q8_state)
q9_state.add_transition(Events['p6'], q0_state)
q9_state.add_transition(Events['t3'], q10_state)
q9_state.add_transition(Events['s5'], q13_state)
q9_state.add_transition(Events['t4'], q9_state)


# create state list
state_list = []
state_list.append(q0_state)
state_list.append(q10_state)
state_list.append(q11_state)
state_list.append(q12_state)
state_list.append(q13_state)
state_list.append(q14_state)
state_list.append(q15_state)
state_list.append(q16_state)
state_list.append(q17_state)
state_list.append(q18_state)
state_list.append(q19_state)
state_list.append(q2_state)
state_list.append(q20_state)
state_list.append(q21_state)
state_list.append(q22_state)
state_list.append(q23_state)
state_list.append(q24_state)
state_list.append(q25_state)
state_list.append(q26_state)
state_list.append(q27_state)
state_list.append(q28_state)
state_list.append(q29_state)
state_list.append(q3_state)
state_list.append(q30_state)
state_list.append(q31_state)
state_list.append(q32_state)
state_list.append(q4_state)
state_list.append(q5_state)
state_list.append(q6_state)
state_list.append(q7_state)
state_list.append(q8_state)
state_list.append(q9_state)


# create event list
alphabet = []
alphabet.append(Events['t4'])
alphabet.append(Events['t3'])
alphabet.append(Events['s5'])
alphabet.append(Events['m6'])
alphabet.append(Events['p6'])
alphabet.append(Events['s1'])
alphabet.append(Events['f5'])
alphabet.append(Events['f1'])


# create supervisor
supE01_liga_cv1 = Supervisor("supE01_liga_cv1", state_list, alphabet)