from .. import Events, State, Supervisor

# Create states
q0_state = State("q0", True)
q10_state = State("q10", False)
q11_state = State("q11", False)
q12_state = State("q12", False)
q13_state = State("q13", False)
q14_state = State("q14", False)
q15_state = State("q15", False)
q16_state = State("q16", False)
q17_state = State("q17", False)
q18_state = State("q18", False)
q19_state = State("q19", False)
q2_state = State("q2", False)
q20_state = State("q20", False)
q21_state = State("q21", False)
q22_state = State("q22", False)
q23_state = State("q23", False)
q24_state = State("q24", False)
q3_state = State("q3", False)
q4_state = State("q4", False)
q5_state = State("q5", False)
q6_state = State("q6", False)
q7_state = State("q7", False)
q8_state = State("q8", False)
q9_state = State("q9", False)


# Create transitions
q0_state.add_transition(Events['m6'], q13_state)
q0_state.add_transition(Events['s5'], q5_state)
q10_state.add_transition(Events['m6'], q22_state)
q10_state.add_transition(Events['f4'], q4_state)
q10_state.add_transition(Events['f5'], q7_state)
q11_state.add_transition(Events['m6'], q23_state)
q11_state.add_transition(Events['f4'], q5_state)
q11_state.add_transition(Events['f5'], q8_state)
q12_state.add_transition(Events['m6'], q24_state)
q12_state.add_transition(Events['f4'], q6_state)
q12_state.add_transition(Events['f5'], q9_state)
q13_state.add_transition(Events['p6'], q0_state)
q13_state.add_transition(Events['s5'], q17_state)
q14_state.add_transition(Events['s5'], q17_state)
q14_state.add_transition(Events['p6'], q3_state)
q15_state.add_transition(Events['s5'], q18_state)
q15_state.add_transition(Events['s4'], q19_state)
q15_state.add_transition(Events['p6'], q3_state)
q16_state.add_transition(Events['f5'], q13_state)
q16_state.add_transition(Events['p6'], q4_state)
q17_state.add_transition(Events['f5'], q14_state)
q17_state.add_transition(Events['p6'], q6_state)
q18_state.add_transition(Events['f5'], q15_state)
q18_state.add_transition(Events['s4'], q22_state)
q18_state.add_transition(Events['p6'], q6_state)
q19_state.add_transition(Events['f4'], q13_state)
q19_state.add_transition(Events['s5'], q23_state)
q19_state.add_transition(Events['p6'], q7_state)
q2_state.add_transition(Events['m6'], q14_state)
q2_state.add_transition(Events['s5'], q5_state)
q20_state.add_transition(Events['f4'], q14_state)
q20_state.add_transition(Events['s5'], q23_state)
q20_state.add_transition(Events['p6'], q9_state)
q21_state.add_transition(Events['f4'], q15_state)
q21_state.add_transition(Events['s5'], q24_state)
q21_state.add_transition(Events['p6'], q9_state)
q22_state.add_transition(Events['p6'], q10_state)
q22_state.add_transition(Events['f4'], q16_state)
q22_state.add_transition(Events['f5'], q19_state)
q23_state.add_transition(Events['p6'], q12_state)
q23_state.add_transition(Events['f4'], q17_state)
q23_state.add_transition(Events['f5'], q20_state)
q24_state.add_transition(Events['p6'], q12_state)
q24_state.add_transition(Events['f4'], q18_state)
q24_state.add_transition(Events['f5'], q21_state)
q3_state.add_transition(Events['m6'], q15_state)
q3_state.add_transition(Events['s5'], q6_state)
q3_state.add_transition(Events['s4'], q7_state)
q4_state.add_transition(Events['f5'], q0_state)
q4_state.add_transition(Events['m6'], q16_state)
q5_state.add_transition(Events['m6'], q17_state)
q5_state.add_transition(Events['f5'], q2_state)
q6_state.add_transition(Events['s4'], q10_state)
q6_state.add_transition(Events['m6'], q18_state)
q6_state.add_transition(Events['f5'], q3_state)
q7_state.add_transition(Events['f4'], q0_state)
q7_state.add_transition(Events['s5'], q11_state)
q7_state.add_transition(Events['m6'], q19_state)
q8_state.add_transition(Events['s5'], q11_state)
q8_state.add_transition(Events['f4'], q2_state)
q8_state.add_transition(Events['m6'], q20_state)
q9_state.add_transition(Events['s5'], q12_state)
q9_state.add_transition(Events['m6'], q21_state)
q9_state.add_transition(Events['f4'], q3_state)


# create state list
state_list = []
state_list.append(q0_state)
state_list.append(q10_state)
state_list.append(q11_state)
state_list.append(q12_state)
state_list.append(q13_state)
state_list.append(q14_state)
state_list.append(q15_state)
state_list.append(q16_state)
state_list.append(q17_state)
state_list.append(q18_state)
state_list.append(q19_state)
state_list.append(q2_state)
state_list.append(q20_state)
state_list.append(q21_state)
state_list.append(q22_state)
state_list.append(q23_state)
state_list.append(q24_state)
state_list.append(q3_state)
state_list.append(q4_state)
state_list.append(q5_state)
state_list.append(q6_state)
state_list.append(q7_state)
state_list.append(q8_state)
state_list.append(q9_state)


# create event list
alphabet = []
alphabet.append(Events['m6'])
alphabet.append(Events['s5'])
alphabet.append(Events['f4'])
alphabet.append(Events['f5'])
alphabet.append(Events['p6'])
alphabet.append(Events['s4'])


# create supervisor
supE06_avanca_braco = Supervisor("supE06_avanca_braco", state_list, alphabet)